### ISSUE TITLE
Storage adapter produces console output for every database query

### ISSUE THREAD

**Issue by bdr99** [TDAmeritrade/botbuilder-storage-postgres#15]
Currently, this library outputs to the console for every db query it makes, and as a user of this library, there is no way to change that. Users may not want to see the additional console output.

This happens because `sequelize` is initialized without the `logging` option set (see below), which defaults to `console.log`. Potential solutions include setting `logging: false` or providing a way for the user of `botbuilder-storage-postgres` to pass in their own value for the `logging` option.

https://github.com/TDAmeritrade/botbuilder-storage-postgres/blob/30b1b2061204dc14cb0411d020324a5322c73ed0/src/PostgresStorage.ts#L65-L74

**Comment by roeintense** [comment]
@bdr99 @dfarinella-tda should we expose that flag so that instantiating, you can pass in whether you want the logging from the requiring application?

**Comment by bdr99** [comment]
> @bdr99 @dfarinella-tda should we expose that flag so that instantiating, you can pass in whether you want the logging from the requiring application?

I think that would be a good solution. That way, each application requiring `botbuilder-storage-postgres` can pass in whatever logging function it wants, or pass `false` to disable the logging altogether.

**Comment by dfarinella-tda** [comment]
I’m good with that.

**Comment by roeintense** [comment]
Resolved by commit 6409c8d93989bb3c59bdad7cbdb6c5e894d5e07b which correctly exposes sequelize logging config option through postgresStorageConfig.
