### ISSUE TITLE
MongoDbStorage files are getting generated in lib folder

### ISSUE THREAD

**Issue by deepakmahakale** [TDAmeritrade/botbuilder-storage-postgres#17]
I am not sure why this is happening but I can see this inside the package.

![image](https://user-images.githubusercontent.com/14993828/71638176-bc9b0980-2c7e-11ea-93c0-839ec63714f4.png)

```
lib/MongoDbStorage.d.ts
lib/MongoDbStorage.js
lib/MongoDbStorage.js.map
```

I can see the following in azure-pipelines 
```diff
     # Publish
     - task: PublishBuildArtifacts@1
-      displayName: 'Publish Artifact: MongoDbStorage'
+      displayName: 'Publish Artifact: PostgresStorage'
       inputs:
           PathtoPublish: package
-          ArtifactName: MongoDbStoragePackage
+          ArtifactName: PostgresStoragePackage
```

**Comment by roeintense** [comment]
Yeah, those are odd. It's likely something left over from a poor build. I will take a look tomorrow.

**Comment by roeintense** [comment]
@deepakmahakale I checked and rechecked, not seeing where those would be built. Could be that they were packaged at some point. I deleted them locally and did a publish with a 1.1.2 increment. Please pull changes and update to 1.1.2 and let me know what you see.

**Comment by roeintense** [comment]
@deepakmahakale following up, please advise if after updating, you no longer see those files.

**Comment by deepakmahakale** [comment]
Hi @roeintense 

I did pull the latest master branch and ran `npm build` I don't see the files for mongo anymore
