### ISSUE TITLE
Continuous integration with Azure Pipelines

### ISSUE THREAD

**Issue by roeintense** [TDAmeritrade/botbuilder-storage-postgres#2]
Would like to get this integrated with Azure Pipelines. Previous `botbuilder-storage-mongodb` pipelines .yml is present, but could be adjusted to fit and build and work AP wizardry for this module.

**Comment by davecramer** [comment]
Presumably you would need a PostgreSQL Azure account?

**Comment by dfarinella-tda** [comment]
Closing issue as we're going to use github actions
